title: "The first day in the last days"
createdAt: "2026-01-26T00:00:00Z"
modifiedAt: "2026-01-26T00:00:00Z"
summary: |
  Ngày đầu đi làm của tôi lại rơi vào những ngày cuối năm – khi team đang chậm lại, ít người online và mọi thứ giống như đang ở chế độ “maintenance”. Một trải nghiệm onboarding khá lạ, khiến tôi nhận ra việc bắt đầu trong một hệ thống đã vận hành sẵn mang đến góc nhìn rất khác. Cảm giác như đến muộn một nhịp, nhưng lại là khởi đầu cho một hành trình mới.
tags: 
  - "Life style"
  - "Ridiculous"
catalog: "blog"